### PR TITLE
Explore 2

### PR DESCRIPTION
**Pull request by Sharmaryan**
user
1.  can filter recent posts
2. can filter trending posts
3. will not be able to post empty

- styled navbar, sidebar, and suggested users section

### CODE REVIEW

**Review by ankit9015 — APPROVED** [review]
Overall the code is clean and good to merge

**Review by TejasShekar — APPROVED** [review]
Looks good. Good folder structure.

**Review by preethasri — COMMENTED** [review]
Good to merge. Functionality working fine

**Comment by saketkum11** [comment]
-Clean code
- easy to understand
- good approach of using api calls

**Review by saketkum11 — APPROVED** [review]

**Pull request merged**
